FROM scratch
ARG DISTURL
LABEL org.openbuildservice.disturl=$DISTURL
LABEL org.opensuse.reference=registry.opensuse.org/asdf/lol:42.0.2.1
LABEL org.opensuse.cbc.proper-base.reference=registry.opensuse.org/asdf/lol:42.0.2.1
