FROM c-b-c-tests/proper-base
LABEL org.openbuildservice.disturl="obs://build.opensuse.org/home:favogt:container-checks/containerfile/e6f02b3d61214e205f11d1c2075b14cc-dockerfile-application-container"
LABEL org.opencontainers.image.created="2021-05-21T14:28:22.338350130Z"
LABEL org.opencontainers.image.description="This contains nano 5.7"
LABEL org.opencontainers.image.title="Example container"
LABEL org.opencontainers.image.version="5.7"
LABEL com.opensuse.example.created="2021-05-21T14:28:22.338350130Z"
LABEL com.opensuse.example.description="This does not contain nano 5.7"
LABEL com.opensuse.example.reference="registry.opensuse.org/opensuse/example:5.7"
LABEL org.opensuse.reference="registry.opensuse.org/opensuse/example:5.7"
COPY some-file /some-file
