FROM scratch
LABEL org.openbuildservice.disturl="not obs://build.opensuse.org/openSUSE:Factory/images/e1b24f5d6cbf69cb7f8208acb618a4fe-opensuse-tumbleweed-image:docker"
LABEL org.opencontainers.image.created="invalid 2021-05-20T00:23:03.624005870Z"
LABEL org.opencontainers.image.description="Not an image containing a minimal environment for containers based on openSUSE Tumbleweed."
LABEL org.opencontainers.image.title="Not openSUSE Tumbleweed Base Container"
LABEL org.opencontainers.image.url="not a url"
LABEL org.opencontainers.image.version="20210519"
LABEL org.opensuse.reference="notregistry.opensuse.org/opensuse/nottumbleweed:latest"
COPY some-file /some-file
