name: Test + Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        include:
          # SLE and Leap 15.x uses python 3.6
          - container: registry.opensuse.org/opensuse/leap:15.6
          # SLE 16.0 uses python 3.13
          - container: registry.suse.com/bci/bci-base:16.0
          # TW uses python 3.13 (as of this writing)
          - container: registry.opensuse.org/opensuse/tumbleweed
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      options: --privileged
    steps:
    - name: Install dependencies
      run: |
        zypper in -y diffutils gzip make tar podman python3-flake8
    - uses: actions/checkout@v6
    - name: Lint
      run: make lint
    - name: Test
      run: make test
